name: Build Debian Package

on:
  push: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "install.sh /usr/local/bin" > debian/install

      - name: Build Debian package
        uses: jtdor/build-deb-action@v1.2.0
        with:
          package_dir: './'
          artifacts_dir: './output'

      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: ./output/*.deb
